#!/usr/bin/env python3
"""Guided setup for deploy/ansible/playbook.yml.

Only prompts for what the playbook actually uses today (see README.md's
"How setup.py works") -- no placeholder questions about things nothing
currently branches on. Writes inventory.ini and group_vars/all/vault.yml
(both already gitignored), then runs ansible-playbook. Re-running this is
safe: it asks before overwriting either file.

Usage:
    python3 setup.py             # interactive
    python3 setup.py --dry-run   # show what would be written/run, do nothing
"""

import argparse
import getpass
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
INVENTORY_PATH = HERE / "inventory.ini"
VAULT_PATH = HERE / "group_vars" / "all" / "vault.yml"


def ask(prompt, default=None, secret=False):
    suffix = f" [{default}]" if default else ""
    reader = getpass.getpass if secret else input
    while True:
        value = reader(f"{prompt}{suffix}: ").strip()
        if value:
            return value
        if default is not None:
            return default
        print("  (required)")


def ask_yes_no(prompt, default=False):
    suffix = "[Y/n]" if default else "[y/N]"
    value = input(f"{prompt} {suffix}: ").strip().lower()
    if not value:
        return default
    return value in ("y", "yes")


def ask_choice(prompt, options):
    """options: list of (key, description). Returns the chosen key."""
    print(prompt)
    for i, (_, desc) in enumerate(options, 1):
        print(f"  [{i}] {desc}")
    while True:
        raw = input(f"> ").strip()
        if raw.isdigit() and 1 <= int(raw) <= len(options):
            return options[int(raw) - 1][0]
        print(f"  enter a number 1-{len(options)}")


def confirm_overwrite(path):
    if not path.exists():
        return True
    return ask_yes_no(f"{path} already exists — overwrite it?", default=False)


def build_inventory():
    print("\n1) Where should this deploy to?")
    target = ask_choice("", [
        ("remote", "A remote instance over SSH"),
        ("local", "This machine (no SSH hop)"),
    ])
    if target == "local":
        return "[speech_cascade]\nlocalhost ansible_connection=local\n"

    host = ask("SSH host (IP or hostname)")
    port = ask("SSH port", default="22")
    user = ask("SSH user", default="root")
    return f"[speech_cascade]\nfresh-instance ansible_host={host} ansible_port={port} ansible_user={user}\n"


def build_vault_and_extra_vars():
    print("\n2) How should model checkpoints/engines be obtained?")
    build_source = ask_choice("", [
        ("s3", "Restore pre-built engines from S3 (fast, needs bucket access)"),
        ("scratch", "Build from scratch on this instance (no bucket access needed, real GPU time)"),
    ])

    vault_lines = ["---", "# Generated by setup.py -- see group_vars/all/vault.yml.example for what each key is."]
    extra_vars = {"build_source": build_source}

    if build_source == "s3":
        print("\nAWS credentials (read access to the S3 bucket in group_vars/all/vars.yml):")
        vault_lines.append(f'vault_aws_access_key_id: "{ask("AWS access key ID")}"')
        vault_lines.append(f'vault_aws_secret_access_key: "{ask("AWS secret access key", secret=True)}"')
    else:
        print(
            "\nHF token for NVFP4 quantization -- must be from an account that has\n"
            "accepted the gated nvidia/Nemotron-Post-Training-Dataset-v2 dataset's\n"
            "terms (used for calibration), not just any token."
        )
        vault_lines.append(f'vault_hf_token: "{ask("Hugging Face token", secret=True)}"')

    print(
        "\n3) GitHub token to clone this repo onto the target?\n"
        "   Leave blank if the target already has it checked out, or has its\n"
        "   own GitHub SSH access configured."
    )
    github_token = ask("GitHub token (optional)", default="", secret=True)
    if github_token:
        vault_lines.append(f'vault_github_token: "{github_token}"')

    if ask_yes_no("\n4) Run the integration test suite once deployment finishes?", default=False):
        extra_vars["run_integration_tests"] = "true"

    return "\n".join(vault_lines) + "\n", extra_vars


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Show the files that would be written and the command that would run, without doing either.",
    )
    args = parser.parse_args()

    for tool in ("ansible-playbook", "ansible-vault"):
        if not shutil.which(tool):
            sys.exit(f"error: {tool} not found on PATH -- install Ansible first (pip install ansible-core).")

    print("Speech Cascade -- guided Ansible setup\n" + "=" * 39)

    inventory_content = build_inventory()
    vault_content, extra_vars = build_vault_and_extra_vars()

    print("\n5) Vault password (encrypts this run's secrets file -- not stored anywhere by this script):")
    vault_password = ask("Vault password", secret=True)

    extra_vars_str = " ".join(f"-e {k}={v}" for k, v in extra_vars.items())
    command = f"ansible-playbook -i {INVENTORY_PATH.name} playbook.yml --vault-password-file <temp> {extra_vars_str}".strip()

    print("\n--- about to write ---")
    print(f"{INVENTORY_PATH} (plaintext)")
    print(f"{VAULT_PATH} (vault-encrypted)")
    print("\n--- about to run ---")
    print(command)

    if args.dry_run:
        print("\n--dry-run: stopping here, nothing written or run.")
        return

    if not ask_yes_no("\nProceed?", default=False):
        print("Aborted.")
        return

    if confirm_overwrite(INVENTORY_PATH):
        INVENTORY_PATH.write_text(inventory_content)
    else:
        print(f"Leaving existing {INVENTORY_PATH} untouched.")

    write_vault = confirm_overwrite(VAULT_PATH)
    if write_vault:
        VAULT_PATH.parent.mkdir(parents=True, exist_ok=True)
        VAULT_PATH.write_text(vault_content)
    else:
        print(f"Leaving existing {VAULT_PATH} untouched.")

    # Vault password only ever touches disk in this one temp file, deleted
    # in the finally block below regardless of how the run ends.
    fd, pw_path = tempfile.mkstemp(prefix="speech-cascade-vault-pw-")
    try:
        os.write(fd, vault_password.encode())
        os.close(fd)
        os.chmod(pw_path, 0o600)

        if write_vault:
            subprocess.run(
                ["ansible-vault", "encrypt", "--vault-password-file", pw_path, str(VAULT_PATH)],
                check=True,
            )

        cmd = [
            "ansible-playbook", "-i", INVENTORY_PATH.name, "playbook.yml",
            "--vault-password-file", pw_path,
        ]
        for k, v in extra_vars.items():
            cmd += ["-e", f"{k}={v}"]
        subprocess.run(cmd, check=True, cwd=HERE)
    finally:
        os.remove(pw_path)


if __name__ == "__main__":
    main()
